---
cdn_transcode_git_url: "https://github.com/OpenVisualCloud/CDN-Transcode-Sample.git"
cdn_transcode_version: "master"
cdn_transcode_dir: "/usr/src/cdn-transcode"
cdn_transcode_cert_dir: "{{ cdn_transcode_dir }}/deployment/certificate"
cdn_transcode_k8s_dir: "{{ cdn_transcode_dir }}/deployment/kubernetes"
cdn_transcode_volume_dir: "{{ cdn_transcode_dir }}/volume/video/archive"
cdn_transcode_service_node_port_range: "1-65535"

cdn_transcode_service_yaml: "cdn-service-service.yaml"
cdn_kafka_service_yaml: "kafka-service-service.yaml"
cdn_redis_service_yaml: "redis-service-service.yaml"
cdn_zookeeper_service_yaml: "zookeeper-service-service.yaml"

cdn_transcode_deploy_yaml: "cdn-service-deployment.yaml"
cdn_kafka_deploy_yaml: "kafka-service-deployment.yaml"
cdn_redis_deploy_yaml: "redis-service-deployment.yaml"
cdn_zookeeper_deploy_yaml: "zookeeper-service-deployment.yaml"
cdn_vod_deploy_yaml: "vod-service-deployment.yaml"
cdn_live_deploy_yaml: "live-service-deployment.yaml"

cdn_ssl_cert_yaml: "self-signed-certificate.yaml"
cdn_generic_deploy_yaml: "-service-deployment.yaml"
