---
# install workloads
- hosts: kube-node
  tasks: []
  roles:
    - role: cluster_defaults
      tags: defaults
  environment: "{{ proxy_env | d({}) }}"
  any_errors_fatal: true

- hosts: k8s-cluster
  tasks: []
  roles:
    - role: cluster_defaults
      tags: defaults
    - role: cdn_transcode_install
      tags: cdn-install
      when: cdn_transcode_enabled | default(false)
    - role: ad_insertion_install
      tags: ad-insert-install
      when: ad_insertion_enabled | default(false) 
    - role: smart_city_install
      when: smtc_enabled | default(false)
    - role: vcmts_install
      when: vcmts_enabled | default (false)
  environment: "{{ proxy_env | d({}) }}"

- hosts: openness-cluster
  tasks: []
  roles:
    - role: ad_insertion_install
      tags: ad-insert-install
      when: openness_enabled | default(false) and ad_insertion_enabled | default(false)
    - role: openness_postinstall
      when: openness_enabled | default(false)
