---
- name: Update /etc/hosts format
  replace:
    path: "/etc/hosts"
    regexp: "(.+){{ item }}"
    replace: "\\1{{ item }} {{ hostvars[inventory_hostname]['ansible_nodename'] }}"
  with_items:
    - "localhost4.localdomain4"
    - "localhost6.localdomain6"
  
- name: Disable SWAP (current session) (1/2)
  command: swapoff -a

- name: Disable SWAP (in /etc/fstab) (2/2)
  replace:
    path: /etc/fstab
    regexp: '(.*swap.*)$'
    replace: '# \1'

- name: retrieve mgmt subnet
  shell: "ip route | grep {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  register: mgmt_route

- set_fact:
    mgmt_subnet: "{{mgmt_route.stdout | regex_search('(.*0/.*) dev', '\\1') }}"

- name: get dataplane interface devices
  command: "lspci -d {{ nic_device_info }}"
  register: dataplane_device_list
  when:
    - smtc_enabled
    - openness_external_dataplane
    - "'edgenode_group' in group_names"

- set_fact:
    office_dataplane_device: "{{ dataplane_device_list.stdout_lines[nic_port].split(' ')[0] }}"
  when:
    - smtc_enabled
    - openness_external_dataplane
    - "'edgenode_group' in group_names"

- name: get interface of primary dataplane device
  shell: "lshw -class network | grep -A 1 {{ office_dataplane_device }}"
  register: dataplane_interface_list
  when:
    - smtc_enabled
    - openness_external_dataplane
    - "'edgenode_group' in group_names"

- set_fact:
    office_dataplane_interface: "{{ dataplane_interface_list.stdout_lines[1] | regex_replace('\\s+logical name: ', '') }}"
  when:
    - smtc_enabled
    - openness_external_dataplane
    - "'edgenode_group' in group_names"

- name: enable dataplane interface
  command: "ip link set {{ office_dataplane_interface }} up"
  when:
    - smtc_enabled
    - openness_external_dataplane
    - "'edgenode_group' in group_names"

#Sync system clocks

