---
- name: refresh repository cache
  apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: install packages
  action: "{{ ansible_pkg_mgr }} name={{ install_dependencies[ansible_os_family] }} state=latest"
  register: pkg_mgr_results
  retries: 3
  until: pkg_mgr_results is success
