---
## Workload playbook variables ##

# General
pexpect_version: "3.3"
pexpect_package: "pexpect=={{ pexpect_version }}"
disable_docker_tty: false

# Smart-City
smtc_enabled: true
smtc_namespace: default
smtc_default_version: master
smtc_sriov_enabled: false
smtc_dir: "/usr/src/smart-city"
smtc_helm_enabled: false
#traffic or stadium
#traffic,stadium for combination
smtc_scenario: traffic
#Xeon or VCAC-A
smtc_platform: Xeon
#Number of Offices (1-3)
smtc_num_offices: 2
#Number of Cameras (1-8) for traffic; (1-8,1-8) for stadium (i.e. 4 for people, 5 for crowd)
smtc_num_cameras: 5
#Number of Analytic Instances (1-8) for traffic; (1-8,1-8) for stadium (i.e. 4 for people, 5 for crowd)
smtc_num_analytics: 5
#gst or ffmpeg
smtc_framework: gst
#cloud labels
cloud_labels: ["cloud-zone","cloud-storage"]
#zone and storage labels for each num of offices defined above
office_labels: ["office1-zone","office1-storage","office2-zone","office2-storage"]
