---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networks.kubernetes.com
  annotations:
    "helm.sh/hook": crd-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  group: kubernetes.com
  version: v1
  scope: Namespaced
  names:
    plural: networks
    singular: network
    kind: Network
    shortNames:
    - net

