---
openness_cur_dir: "openness-current"
openness_next_dir: "openness-next"
openness_dir: "{%- if openness_current_enabled -%}{{ openness_cur_dir }}{%- elif openness_next_enabled -%}{{ openness_next_dir }}{%- endif -%}"
openness_groupvars_all: "../{{ openness_dir }}/group_vars/all.yml"
openness_groupvars_ctrl: "../{{ openness_dir }}/group_vars/controller_group.yml"
openness_groupvars_node: "../{{ openness_dir }}/group_vars/edgenode_group.yml"

openness_cur_branch: "openness-20.03"
openness_next_branch: "master"
openness_branch: "{%- if openness_current_enabled -%}{{ openness_cur_branch }}{%- elif openness_next_enabled -%}{{ openness_next_branch }}{%- endif -%}"

openness_playbook: "../{{ openness_dir }}/network_edge.yml"
