---
########TODO#########
#- name: update node selector
#  lineinfile:
#    dest: "{{ ad_insertion_k8s_dir }}/{{ item }}"
#    regexp: '        kubernetes.io/hostname: (.*)'
#    line: '        kubernetes.io/hostname: {{ groups["kube-node"][0] }}'
#    state: present
#  with_items:
#    - "{{ deploy_all_list }}"    
#################

- name: update volume paths
  replace:
    path: "{{ ad_insertion_k8s_dir }}/{{ item }}"
    regexp: '(.+)path:\s/home/vcse/ADI/fork/Ad-Insertion-Sample(.+)'
    replace: '\1path: {{ ad_insertion_dir }}\2'
  with_items:
    - "ad-transcode-deployment.yaml"
    - "ad-insertion-frontend-deployment.yaml"
    - "ad-content-deployment.yaml"
    - "content-provider-deployment.yaml"
    - "content-provider-transcode-deployment.yaml"

###TODO###
#- name: add gpu resource limits if hw defined
##########

- name: generate k8s ssl cert keys
  shell: "{{ ad_insertion_cert_dir }}/self-sign.sh"
  args:
    creates: self.key

- name: create ssl certificates yaml
  shell: 'kubectl create secret generic ssl-key-secret --from-file=self.key="{{ ad_insertion_cert_dir }}/self.key" --from-file=self.crt="{{ ad_insertion_cert_dir }}/self.crt" --from-file=dhparam.pem="{{ ad_insertion_cert_dir }}/dhparam.pem" --dry-run -o yaml > "{{ ad_insertion_k8s_dir }}/{{ ad_insertion_ssl_cert_yaml }}"'
  args:
    chdir: "{{ ad_insertion_dir }}"
    creates: "{{ ad_insertion_ssl_cert_yaml }}"

######TODO########
#- name: add namespace identifier
#  lineinfile:
#    dest: "{{ cdn_transcode_k8s_dir }}/{{ item }}"
#    line: '  namespace: {{ cdn_transcode_namespace }}'
#    insertbefore: '\s+creationTimestamp:.*'
#    firstmatch: yes 
#  with_items:
#    - "{{ service_all_list }}"
#    - "{{ deploy_all_list }}"
#    - "{{ cdn_ssl_cert_yaml }}"

#- set_fact:
#    net_annotation_lines: []

#- set_fact:
#    net_annotation_lines: "{{ net_annotation_lines }} + [ '{{ item }}' ]"
#  with_items:
#    - "      annotations:"
#    - "        k8s.v1.cni.cncf.io/networks: \\'["
#    - "              { \"name\": \"flannel-net\" },"
#    - "              { \"name\": \"sriov-net\" }"
#    - "        ]\\'"

#- name: add SRIOV network annotations
#  lineinfile:
#    dest: "{{ cdn_transcode_k8s_dir }}/{{ item[0] }}"
#    line: "{{ item[1] }}"
#    insertbefore: '\s+labels:'
#  with_nested:
#    - "{{ deploy_all_list }}"
#    - "{{ net_annotation_lines }}"
#  when:
#    - sriov_net_dp_enabled

#- name: add SRIOV VF limits and requests
#  lineinfile:
#    dest: "{{ cdn_transcode_k8s_dir }}/{{ item[0] }}"
#    line: "            intel.com/intel_sriov_netdevice: {{ item[1].count }}"
#    insertafter: "{{ item[1].regex }}"
#  with_nested:
#    - "{{ deploy_all_list }}"
#    - [
#        { regex: '\s+limits:', count: "\'1\'" },
#        { regex: '\s+requests:', count: "\"1\"" }
#      ]
#  when: 
#    - sriov_net_dp_enabled
####################
