---
- name: install base packages on camera nodes
  import_role:
    name: "{{ bmra_preconfigure_role }}/k8s-all-preconfigure"
  when: 
    - openness_external_dataplane
    - bmra_current_enabled

- name: install additional dependencies
  include_role:
    name: install-dependencies
  when: openness_external_dataplane

- name: install docker on camera nodes
  import_role:
    name: "{{ openness_docker_role }}"
  vars:
    offline_mode: false
    proxy_os_enable: true
    proxy_os_http: "{{ http_proxy }}"
    proxy_os_https: "{{ https_proxy }}"
    proxy_os_ftp: "{{ http_proxy }}"
    proxy_os_noproxy: "{{ no_proxy }}"
  when: openness_external_dataplane

- name: clone and build Smart-City
  import_role:
    name: smart-city-make
  when: openness_external_dataplane

- name: start smart-city openness camera
  command: make start_openness_camera
  args:
    chdir: "{{ smtc_dir }}/build"
