---
- set_fact:
    camera_num: "{{ groups.cameras.index(inventory_hostname) | int + 1 }}"

- set_fact:
    camera_ip: "192.168.{{ camera_num }}.10"

- name: get dataplane interface devices
  command: "lspci -d {{ nic_device_info }}"
  register: dataplane_device_list

- set_fact:
    camera_dataplane_device: "{{ dataplane_device_list.stdout_lines[nic_port].split(' ')[0] }}"

- name: get interface of primary dataplane device
  shell: "lshw -class network | grep -A 1 {{ camera_dataplane_device }}"
  register: dataplane_interface_list

- set_fact:
    camera_dataplane_interface: "{{ dataplane_interface_list.stdout_lines[1] | regex_replace('\\s+logical name: ', '') }}"

- name: enable dataplane interface
  command: "ip link set {{ camera_dataplane_interface }} up"

- name: assign ip to dataplane interface
  command: "ip a add {{ camera_ip }}/24 dev {{ camera_dataplane_interface }}"
  ignore_errors: true

- name: add route to openness gateway
  command: "route add -net 10.16.0.0/24 gw 192.168.{{ camera_num }}.1 dev {{ camera_dataplane_interface }}"
  ignore_errors: true
